version: '3'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'overpayment-postgres-db'
    environment:
      - 'POSTGRES_DB: overpayment'
      - 'POSTGRES_USER: root'
      - 'POSTGRES_PASSWORD: 654321'
    volumes:
      -

  app:
    build: ./
    container_name: 'overpayment-app'
    ports:
      - 8098:8098